# Generated by Django 4.0.5 on 2022-06-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gas_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=20)),
                ('plate_number', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('permited_amount', models.IntegerField()),
                ('used_amount', models.IntegerField()),
                ('left_amount', models.IntegerField()),
                ('qr_code', models.CharField(max_length=20)),
            ],
        ),
    ]
