# Generated by Django 4.0.5 on 2022-06-20 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('identifier', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='gas_offer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gas_offer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gas_offer',
            name='file_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='gas_offer',
            name='plate_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gas_offer',
            name='qr_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gas_offer',
            name='gasstation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.gasstation'),
        ),
    ]
