# Generated by Django 4.0.3 on 2022-06-27 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audited',
            name='total_filled',
        ),
        migrations.RemoveField(
            model_name='audited',
            name='total_money',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='gasstation',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='money_reciever',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='total_compensated',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='total_money',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='user',
        ),
        migrations.AddField(
            model_name='audited',
            name='compansating_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audited',
            name='compensated_benzen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audited',
            name='compensated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audited',
            name='compensated_petrol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audited',
            name='money_for_benzene',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audited',
            name='money_for_petrol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audited',
            name='money_reciever',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='audited',
            name='total_compensated_fuel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audited',
            name='total_money_compansated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='audited',
            name='gasstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offer.gasstation'),
        ),
        migrations.AlterField(
            model_name='audited',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log_table',
            name='audited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='offer.audited'),
        ),
        migrations.AlterField(
            model_name='log_table',
            name='compensated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='offer.compensation'),
        ),
        migrations.AlterField(
            model_name='log_table',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle', to='offer.gas_offer'),
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('benzene', 'Benzene'), ('petrol', 'Petrol')], max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gas_offer',
            name='fuel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='offer.fuel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log_table',
            name='fuel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='offer.fuel'),
            preserve_default=False,
        ),
    ]
