# Generated by Django 4.0.5 on 2022-06-21 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0002_gasstation_gas_offer_user_alter_gas_offer_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gas_offer',
            name='gasstation',
        ),
        migrations.RemoveField(
            model_name='gas_offer',
            name='left_amount',
        ),
        migrations.RemoveField(
            model_name='gas_offer',
            name='used_amount',
        ),
        migrations.RemoveField(
            model_name='gas_offer',
            name='user',
        ),
        migrations.AddField(
            model_name='gas_offer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='log_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('filled_amount', models.IntegerField()),
                ('gasstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.gasstation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_amount', models.IntegerField()),
                ('left_amount', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('gasstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.gasstation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offer.gas_offer')),
            ],
        ),
    ]
