# Generated by Django 4.0.5 on 2022-06-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_gas_offer_gasstation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyusage',
            name='gasstation',
        ),
    ]
