# Generated by Django 4.0.3 on 2022-06-28 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0003_audited_audit_date_from_audited_audit_date_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='offer.audited'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='compensation',
            name='financer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='financer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensation',
            name='gasstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gasstation', to='offer.gasstation'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='total_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
