# Generated by Django 4.0.3 on 2022-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_compensation_audit_compensation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='subsidy_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
