# Generated by Django 4.0.3 on 2022-06-26 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(default=0, null=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('cashier', 'Cashier'), ('auditor', 'Auditor'), ('finance', 'Finance')], max_length=20, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('gasstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.gasstation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
