# Generated by Django 4.0.5 on 2022-06-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_gas_offer_gasstation_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gasstaion',
        ),
        migrations.AddField(
            model_name='profile',
            name='gasstation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.gasstation'),
        ),
    ]
