# Generated by Django 4.0.3 on 2022-06-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_audited_total_filled_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gasstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.gasstation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('cashier', 'Cashier'), ('auditor', 'Auditor'), ('finance', 'Finance'), ('staff', 'Staff')], max_length=20, null=True),
        ),
    ]
